/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#23005c",
        "secondary-fixed-dim": "#d0bcff",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "outline-variant": "#444748",
        "on-secondary": "#3c0091",
        "secondary": "#d0bcff",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#454747",
        "primary-container": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "error": "#ffb4ab",
        "surface-container-highest": "#353434",
        "surface-variant": "#353434",
        "on-error": "#690005",
        "primary": "#ffffff",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#636565",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#3a3939",
        "surface-dim": "#141313",
        "tertiary-container": "#e2e2e2",
        "surface": "#141313",
        "secondary-fixed": "#e9ddff",
        "on-background": "#e5e2e1",
        "on-primary": "#2f3131",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1a1c1c",
        "on-secondary-container": "#c4abff",
        "inverse-primary": "#5d5f5f",
        "surface-tint": "#c6c6c7",
        "tertiary": "#ffffff",
        "on-tertiary": "#2f3131",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "secondary-container": "#571bc1",
        "outline": "#8e9192",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#636565",
        "on-surface-variant": "#c4c7c8",
        "background": "#141313",
        "on-secondary-fixed-variant": "#5516be",
        "accent-purple": "#8b5cf6",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding": "24px",
        "gutter": "1px",
        "unit": "4px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-tech": ["IBM Plex Mono", "monospace"],
        "data-mono-lg": ["IBM Plex Mono", "monospace"],
        "data-mono-sm": ["IBM Plex Mono", "monospace"],
        "label-caps": ["Geist", "sans-serif"]
      },
    },
  },
  plugins: [],
}
